### PR TITLE
Updated dapper files

### PR DESCRIPTION
**Pull request by steffantucker**
Migrated to a SUSE container, a newer version of Go, and using golangci-lint for all linting. Fulfills https://github.com/rancher/tasks/issues/203

### CODE REVIEW

**Review by jiaqiluo — APPROVED** [review]
LGTM

**Comment by jiaqiluo** [comment]
hi @rancher/rancher-team-1-neo-dev @rancher/rancher-team-2-hostbusters-dev  
can we get one more this PR review on this PR? 
after this PR is merged, I can then bump Go to 1.19, which is beneficial for supporting 1.25

**Review by superseb — APPROVED** [review]
It needs another update round but based on your comment, this will be done in a next PR. Please change the `registry.suse.com/bci/golang:1.17` image to an exact version so the update tooling can create PRs to use updates, e.g. `registry.suse.com/bci/golang:1.19-18.38`

**Comment by jiaqiluo** [comment]
> It needs another update round but based on your comment, this will be done in a next PR. Please change the `registry.suse.com/bci/golang:1.17` image to an exact version so the update tooling can create PRs to use updates, e.g. `registry.suse.com/bci/golang:1.19-18.38`

Merging this PR. I am going to handle the changes in the following PR.

**Review by kinarashah — APPROVED** [review]
Merging this to unblock for 1.25 changes. @jiaqiluo I noticed that we are removing `go vet` here, could you check if it's enabled by default and if not, enable it in your next PR?  
An example is here, https://github.com/rancher/rancher/pull/23448/files#diff-7b9967b524b30a7e62fef0e2d0827b63026239c22e6f1c34bfad57d138b26edfR5

**Comment by jiaqiluo** [comment]
`go vet` is enabled by default in `golangci-lint`, so there is no need to enable it 
see https://golangci-lint.run/usage/linters/#:~:text=govet%C2%A0%E2%9A%99%EF%B8%8F,v1.0.0

**Pull request merged**
